version: '3.8'
services:
  chameleon:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./augmented_images:/app/augmented_images
      - ./trained_models:/app/trained_models
    env_file:
      - .env
    environment:
      GENERATION_PROVIDER: local
      LOCAL_MASK_URL: http://mask-generator/v1/images/masks
      LOCAL_GENERATE_URL: http://image-generator/v1/images/edits
      LOCAL_LABEL_URL: http://labeler/v1/images/labels
    depends_on:
      - mask-generator
      - image-generator
      - labeler
    networks:
      - chameleon-net

  mask-generator:
    image: mask-generator:latest
    ports:
      - "8001:80"
    networks:
      - chameleon-net

  image-generator:
    image: image-generator
    ports:
      - "8002:80"
    networks:
      - chameleon-net
    env_file:
      - .env

  labeler:
    image: merfanian/labeler
    ports:
      - "8003:80"
    networks:
      - chameleon-net

networks:
  chameleon-net:
    driver: bridge
